In [ ]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [13]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
List_ datatype is list while
array_list datatype is numpy array

In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [21]:
#For List_
for i in list_:
    print(type(i))

#For array_list
print(array_list.dtype)
for i in array_list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<U1
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [22]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_, dtype = int)


In [27]:
print(type(list_))
print(type(array_list))
#For List_
for i in list_:
    print(type(i))

#For array_list
print(array_list.dtype)
for i in array_list:
    print(type(i))

<class 'list'>
<class 'numpy.ndarray'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
int64
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [ ]:
The datatype of list_ and array_list is still the same i.e. list and array
But
The datatypes of elemts of in array_list are changed to String

In [30]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [29]:
np.shape(num_array)

(2, 3)

In [31]:
np.size(num_array)

6

In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [36]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])